# Generated by Django 4.0.4 on 2022-06-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permissions',
            field=models.CharField(choices=[('manager', 'Manager'), ('contributor', 'Contributeur')], max_length=128),
        ),
    ]
